FROM rust:1.63-bullseye
ADD ./hermes/ /app/network/hermes/
WORKDIR /app
RUN PLATFORM=`uname -a | awk '{print $(NF-1)}'` && \
    curl -L "https://github.com/informalsystems/ibc-rs/releases/download/v0.14.1/hermes-v0.14.1-${PLATFORM}-unknown-linux-gnu.tar.gz" > hermes.tar.gz && \
    mkdir -p $HOME/.hermes/bin && \
    tar -C $HOME/.hermes/bin/ -vxzf hermes.tar.gz && \
    rm -f hermes.tar.gz 
ENV PATH="/root/.hermes/bin:${PATH}"

CMD /app/network/hermes/restore-keys.sh && \
    /app/network/hermes/create-conn.sh && \
    hermes -c /app/network/hermes/config.toml create channel --port-a transfer --port-b transfer test-1 connection-0 && \
    /app/network/hermes/start.sh
