# syntax=docker/dockerfile:1

FROM golang:1.18-bullseye
EXPOSE 26656 26657 1317 9090
COPY --from=app . /opt/neutron
RUN cd /opt/neutron && make install
WORKDIR /opt/neutron
COPY --from=setup . setup/

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD \
    curl -f http://127.0.0.1:1317/blocks/1 >/dev/null 2>&1 || exit 1

CMD sh /opt/neutron/setup/init.sh && \
    sh /opt/neutron/setup/start.sh