FROM ubuntu:rolling AS git-cloner
RUN apt-get update && apt-get install -y git
WORKDIR /src
RUN git clone --branch v1.0.0 https://github.com/skip-mev/slinky.git .

FROM golang:1.22-bullseye AS builder
WORKDIR /src/slinky
COPY --from=git-cloner /src .

RUN go mod download

RUN make build

FROM ubuntu:rolling
EXPOSE 8080
EXPOSE 8002

COPY --from=builder /src/slinky/build/* /usr/local/bin/
RUN apt-get update && apt-get install ca-certificates -y

WORKDIR /usr/local/bin/

ENTRYPOINT ["slinky"]
