FROM golang:1.22-bullseye as builder

ARG LDFLAGS
RUN mkdir /app
WORKDIR /app
COPY --from=app go.mod go.sum ./
RUN go mod download
COPY --from=app . .
RUN go build -ldflags "${LDFLAGS}" -a -o build/neutron_query_relayer ./cmd/neutron_query_relayer/*.go

FROM debian:buster
RUN apt update && apt install ca-certificates curl -y && apt-get clean
ADD ["https://github.com/CosmWasm/wasmvm/releases/download/v1.5.2/libwasmvm.x86_64.so","https://github.com/CosmWasm/wasmvm/releases/download/v1.5.2/libwasmvm.aarch64.so","/lib/"]
COPY --from=app run.sh .
COPY --from=queryrelayer . /data/queryrelayer
COPY --from=builder /app/build/neutron_query_relayer /bin/
EXPOSE 9999

ENTRYPOINT ["neutron_query_relayer", "start"]
